
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://huvmdbffioxhizgzeecd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh1dm1kYmZmaW94aGl6Z3plZWNkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyMDYyNzUsImV4cCI6MjA2NDc4MjI3NX0.uy6D8Y0iweLzhmXOkPG-Jpabbbg-an4jiiXeI5KnyAY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
