// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rwmprtylsoamonnprfsy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ3bXBydHlsc29hbW9ubnByZnN5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4NzYwODgsImV4cCI6MjA2MjQ1MjA4OH0.A4vwyhrNdCHEHR3c7UrOlgLfMfIPGMYtOh7Z-LyOZyk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);